name: CommandBlockerPro
version: '${project.version}'
main: net.jadedmc.commandblockerpro.CommandBlockerProPlugin
api-version: 1.13
folia-supported: true

softdepend:
  - PlaceholderAPI

commands:
  commandblocker:
    description: Main plugin command.
    aliases: [cb,cbp,commandblockerpro]