name: CommandBlockerPro
version: '${project.version}'
main: net.jadedmc.commandblockerpro.CommandBlockerProPlugin
api-version: 1.13
authors: [JadedMC]
description: Prevent specific commands from being used
website: http://www.jadedmc.net
folia-supported: true

softdepend:
  - PlaceholderAPI

commands:
  commandblocker:
    description: Main plugin command.
    aliases: [cb,cbp,commandblockerpro]